version: '2'

services:
  web:
    build: .
    command: python app.py
    ports:
       - "80:5000"
    hostname: hello.weave.local
    network_mode: "bridge"
    environment:
       - "affinity:container!=app_web_*"
  redis:
    image: redis
    hostname: redis.weave.local
    network_mode: "bridge"
