version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end
    hostname: front-end
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - external
      - secure
      - internal
  edge-router:
    image: weaveworksdemos/edge-router
    ports: [ '80:80' ]
    hostname: edge-router
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - external
  catalogue:
    image: weaveworksdemos/catalogue
    hostname: catalogue
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - external
  accounts:
    image: weaveworksdemos/accounts
    hostname: accounts
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - secure
  accounts-db:
    image: mongo
    hostname: accounts-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - secure
  cart:
    image: weaveworksdemos/cart
    hostname: cart
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - internal
  cart-db:
    image: mongo
    hostname: cart-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - internal
  orders:
    image: weaveworksdemos/orders
    hostname: orders
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - internal
      - secure
      - backoffice
  orders-db:
    image: mongo
    hostname: orders-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - internal
  shipping:
    image: weaveworksdemos/shipping
    hostname: shipping
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - backoffice
  queue-master:
    image: weaveworksdemos/queue-master
    hostname: queue-master
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - backoffice
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - backoffice
  payment:
    image: weaveworksdemos/payment
    hostname: payment
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - secure
  login:
    image: weaveworksdemos/login
    hostname: login
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    networks:
      - secure
  weavescope:
    image: weaveworks/scope:0.16.0
    network_mode: host
    pid: host
    privileged: true
    labels: [ 'works.weave.role=system' ]
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock:rw' ]
    command: [ '--no-app', '--probe.docker=true', 'localhost:4040' ]
  weavescope-app:
    image: weaveworks/scope:0.16.0
    ports: [ '4040:4040' ]
    labels: [ 'works.weave.role=system' ]
    command: [ '--no-probe' ]
  load-test:
    image: weaveworksdemos/load-test
    restart: always
    networks:
      - external
    command: [ '-h', 'edge-router', '-r', '1000', '-c', '20' ]

networks:
  external:
    driver: bridge
  secure:
    driver: bridge
  internal:
    driver: bridge
  backoffice:
    driver: bridge
